import assert from "node:assert/strict";

// An explicit boundary prevents accidental API/MCP exposure when routes are added.
export const expectedBrowserOnlyRoutes = new Set([
  "DELETE /gitlab/oauth/connection",
  "DELETE /profile/email-change",
  "DELETE /sessions/:sessionId",
  "DELETE /settings/api-keys/personal/:keyId",
  "DELETE /settings/api-keys/team/:keyId",
  "DELETE /settings/private-keys/:privateKeyId",
  "DELETE /team/invitations/:invitationId",
  "DELETE /team/members/:memberId",
  "GET /deployments/:deploymentId/source-revision",
  "GET /gitlab/oauth/callback",
  "GET /log-drains",
  "GET /monitoring/summary",
  "GET /notifications",
  "GET /notifications/deliveries",
  "GET /notifications/destinations",
  "GET /notifications/providers",
  "GET /profile",
  "GET /profile/email-change",
  "GET /profile/passkeys",
  "GET /profile/preferences",
  "GET /servers/:serverId/scout-alerts/incidents/:incidentId/notifications",
  "GET /sessions",
  "GET /settings/api-keys/personal",
  "GET /settings/api-keys/team",
  "GET /settings/private-keys",
  "GET /settings/private-keys/:privateKeyId/reveal",
  "GET /sources/:sourceId/notifications/deliveries",
  "GET /sources/:sourceId/notifications/destinations",
  "GET /team",
  "GET /team/audit-logs",
  "GET /team/audit-logs/filters",
  "GET /team/invitations",
  "GET /team/members",
  "PATCH /profile",
  "PATCH /settings/private-keys/:privateKeyId",
  "PATCH /team",
  "PATCH /team/members/:memberId",
  "POST /apps/:ownerId/secrets/:environment/:stage/reveal",
  "POST /apps/:ownerId/secrets/:environment/:stage/reveal-all",
  "POST /date-time/localize",
  "POST /github/actions/complete-installation",
  "POST /github/actions/installation-url",
  "POST /gitlab/oauth/start",
  "POST /profile/email-change",
  "POST /profile/preferences/preview",
  "POST /profile/preferences/range",
  "POST /profile/preferences/range/resolve",
  "POST /profile/two-factor/manage",
  "POST /profile/two-factor/setup",
  "POST /resources/:ownerId/secrets/:environment/:stage/reveal",
  "POST /resources/:ownerId/secrets/:environment/:stage/reveal-all",
  "POST /servers/:serverId/terminal",
  "POST /settings/api-keys/personal",
  "POST /settings/api-keys/team",
  "POST /settings/private-keys",
  "POST /settings/secrets/:environment/:stage/reveal",
  "POST /settings/secrets/:environment/:stage/reveal-all",
  "POST /sources/:ownerId/secrets/:environment/:stage/reveal",
  "POST /sources/:ownerId/secrets/:environment/:stage/reveal-all",
  "POST /team/invitations",
  "POST /team/members",
  "PUT /profile/password",
  "PUT /profile/preferences",
]);

export function assertPublicOperationNames(
  operations: Array<{ name: string }>,
) {
  assert.equal(
    new Set(operations.map((op) => op.name)).size,
    operations.length,
  );
  assert.equal(operations.length, 138);
  assert(operations.every((op) => op.name.length <= 64));
}
