version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /tools/distribution
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /apps/towbar-api
      - /apps/towbar-worker
      - /apps/towbar-web-app
      - /examples
      - /examples/persistent-files
      - /examples/platform-modes/node-app
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
